package common

type ServiceConfiguration struct {
	SERVICE_PORT                string `mapstructure:"SERVICE_PORT"`
	SERVICE_NAME                string `mapstructure:"SERVICE_NAME"`
	SERVICE_DOMAIN              string `mapstructure:"SERVICE_DOMAIN"`
	SERVICE_BASEPATH            string `mapstructure:"SERVICE_BASEPATH"`
	SERVICE_VERSION             string `mapstructure:"SERVICE_VERSION"`
	COURSE_COLLECTION 			string `mapstructure:"COURSE_COLLECTION"`
	CHAPTER_COLLECTION 			string `mapstructure:"CHAPTER_COLLECTION"`
	LESSON_COLLECTION			string  `mapstructure:"LESSON_COLLECTION"`
	TOKEN_COLLECTION 			string `mapstructure:"TOKEN_COLLECTION"`
	PERMISSION_COLLECTION		string `mapstructure:"PERMISSION_COLLECTION"`
	MASTERDATA_COLLECTION		string  `mapstructure:"MASTERDATA_COLLECTION"`
	USER_COLLECTION				string  `mapstructure:"USER_COLLECTION"`
	NOTIFICATION_COLLECTION		string `mapstructure:"NOTIFICATION_COLLECTION"`
	AUDIT_COLLECTION			string  `mapstructure:"AUDIT_COLLECTION"`
	DRAFT_COLLECTION			string `mapstructure:"DRAFT_COLLECTION"`
	APPROVAL_COLLECTION			string `mappackage:"APPROVAL_COLLECTION"`
	ADMIN_ROLE                  string `mapstructure:"ADMIN_ROLE"`
	PROFESSOR_ROLE              string `mapstructure:"PROFESSOR_ROLE"`
	STUDENT_ROLE                string `mapstructure:"STUDENT_ROLE"`
	SUPER_ADMIN_ROLE 			string `mapstructure:"SUPER_ADMIN_ROLE"`
	SMTP_SERVER					string `mapstructure:"SMTP_SERVER"`
	SMTP_BASEEMAIL				string `mapstructure:"SMTP_BASEEMAIL"`
	SMTP_PASSKEY				string `mapstructure:"SMTP_PASSKEY"`
	SMTP_PORT					string `mapstructure:"SMTP_PORT"`
	APPROVAL_URL				string `mapstructure:"APPROVAL_URL"`
	GCP_BUCKET					string `mapstructure:"GCP_BUCKET"`
	GCP_PROJECTID				string `mapstructure:"GCP_PROJECTID"`
	GCP_CLIENT_MAIL				string `mapstructure:"GCP_CLIENT_MAIL"`
	GCP_TYPE  					string `mapstructure:"GCP_TYPE"`
	GCP_PRIVATE_KEY				string `mapstructure:"GCP_PRIVATE_KEY"`
	MONGO_DATABASE              string `mapstructure:"MONGO_DATABASE"`
	MONGO_USERNAME				string  `mapstructure:"MONGO_USERNAME"`
	MONGO_PASSWORD				string   `mappackage:"MONGO_PASSWORD"`
	MONGO_PORT					string   `mapstructure:"MONGO_PORT"`
	MONGO_HOST					string    `mapstructure:"MONGO_HOST"`
	SERVICE_DESCRIPTION         string `mapstructure:"SERVICE_DESCRIPTION"`
	SERVICE_HOST                string `mapstructure:"SERVICE_HOST"`
	JAEGER_URL                  string `mapstructure:"JAEGER_URL"`
	TRACER_ENABLED              string `mapstructure:"TRACER_ENABLED"`
	GCP_PROJECT_ID              string `mapstructure:"GCP_PROJECT_ID"`
	GCP_AUTHORIZATION_TYPE      string `mapstructure:"GCP_AUTHORIZATION_TYPE"`
	PUBSUB_SUBSCRIPTION         string `mapstructure:"PUBSUB_SUBSCRIPTION"`
	PUBSUB_TOPIC                string `mapstructure:"PUBSUB_TOPIC"`
	GATEWAY_PUBLIC_KEY          string `mapstructure:"GATEWAY_PUBLIC_KEY"`
	GATEWAY_PRIVATE_KEY         string `mapstructure:"GATEWAY_PRIVATE_KEY"`
	AUDIT_SERVICE               string `mapstructure:"AUDIT_SERVICE"`
	FANOUT_SERVICE              string `mapstructure:"FANOUT_SERVICE"`
	REDIS_HOST                  string `mapstructure:"REDIS_HOST"`
	REDIS_PORT                  string `mapstructure:"REDIS_PORT"`
	REDIS_NAME                  string `mapstructure:"REDIS_NAME"`
	REDIS_PASSWORD              string `mapstructure:"REDIS_PASSWORD"`
	REDIS_TOKEN_COLLECTION      string `mapstructure:"REDIS_TOKEN_COLLECTION"`
	REDIS_AUTHMECHANISAM        string `mapstructure:"REDIS_AUTHMECHANISAM"`
	LOOKUP_SERVICE              string `mapstructure:"LOOKUP_SERVICE"`
	DEFAULT_SENDER_SUBCRIBER_ID string `mapstructure:"DEFAULT_SENDER_SUBCRIBER_ID"`
	DEFAULT_SIGNATURE           string `mapstructure:"DEFAULT_SIGNATURE"`
	DEFAULT_REQUEST_ID          string `mapstructure:"DEFAULT_REQUEST_ID"`
	VLOOKUP_URL                 string `mapstructure:"VLOOKUP_URL"`
	DEFAULT_COUNTRY             string `mapstructure:"DEFAULT_COUNTRY"`
	VLOOKUP_SIGNATURE_URL       string `mapstructure:"VLOOKUP_SIGNATURE_URL"`
	VLOOKUP_PRIVATE_KEY         string `mapstructure:"VLOOKUP_PRIVATE_KEY"`
}
