name: Build and Deploy BO User

on:
  push:
    branches:
      - bo-users

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout bo-user branch
        uses: actions/checkout@v2
        with:
          ref: bo-users
      
      - name: Checkout main branch
        uses: actions/checkout@v2
        with:
          ref: main

      - name: Merge bo-user into main
        run: git merge --no-ff --no-edit bo-users

      - name: Change directory to Dockerfile location
        run: cd lms/backoffice/backend/user
      
      - name: Docker Build
        run: docker build -t your_image_name .

      - name: Login to GCP Artifact Registry
        run: gcloud auth configure-docker asia-south1-docker.pkg.dev

      - name: Docker Push to Artifact Registry
        run: |
          docker tag your_image_name gcr.io/your_project_id/your_image_name
          docker push gcr.io/your_project_id/your_image_name

      - name: SSH into GCP Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            docker pull gcr.io/your_project_id/your_image_name
            docker run -d --name your_container_name -p 80:80 gcr.io/your_project_id/your_image_name
