name: Build and Deploy BO User

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: SSH into GCP Compute Engine
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            git pull
            cd lms/lms/backoffice/backend/user
            latest_tag=$(sudo docker images your_image_name --format "{{.Tag}}" | head -n 1)
            echo $latest_tag
            majorversion=$(echo $latest_tag | cut -d "." -f 1)
            minorversion=$(echo $latest_tag | cut -d "." -f 2)
            patch=$(echo $latest_tag | cut -d "." -f 3)
            tag=$((patch+1))
            newtag="$majorversion.$minorversion.$tag"
            echo $newtag
            imagename="user:$newtag"
            echo $imagename
            sudo docker build -t $imagename .
            sudo docker run -d --name bo-user -p 4002:4002 asia-south1-docker.pkg.dev/peaceful-harbor-416116/lms/$imagename
